### ISSUE TITLE
Adapter spams syslog at night

### ISSUE THREAD

**Issue by asgothian** [woessmich/ioBroker.weatherflow_udp#16]
Hey,

I've been using the adapter pretty much since day 1, and it is working fine. There is one inconvenience: At night (with brightness being very low), I keep seeing these messages, one every minute as long as it is dark enough.

I did verify that the messages appear only if
- the reported Brightness is 0
- the adapter is running.

`Jan  3 19:22:09 groenlund bash[17776]: [Groenlund E62D@Tempest@@Current Ambient Light Level] characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001`

In winter, these messages alone generate approx. 150 kb data (per Log) in 2 logs:
- syslog.log
- daemon.log

In order to minimise sd card writes, I would very much like to get rid of them, but looking through the code I could not identify any possible cause.

A.

**Comment by woessmich** [comment]
Hi

This sounds like a similar issue as that one:
[https://github.com/arachnetech/homebridge-mqttthing/issues/414](url)

I understand that homebridge is causing this logs.
Do you forward the brightness data to homebridge somehow?
If yes, you may want not to send 0 values but limit to not less than the 0.0001.

**Comment by asgothian** [comment]
Thanks, seems that was the reason. I didn't think to look there.

A.
